//
//  ClipItem+Extensions.swift
//  ClipVault
//
//  Created by Edd on 09/10/2025.
//

import Foundation
import CoreData
import AppKit
import ImageIO

// Note: Core Data properties are auto-generated by Xcode in ClipItem+CoreDataProperties.swift
// This file defines the class and adds convenience extensions

@objc(ClipItem)
public class ClipItem: NSManagedObject {
    private var metadataCache: (id: UUID, ciphertext: Data, metadata: ClipMetadata)?
    // Properties are defined in the auto-generated ClipItem+CoreDataProperties.swift
}

struct ClipMetadata: Codable {
    var version = 1
    var dateAdded: Date?
    var firstCapturedAt: Date?
    var appBundleID: String?
    var imageType: String?
    var imageByteCount: Int64 = 0
    var contentHash: String?
}

// MARK: - Convenience Extensions

extension ClipItem {

    private static let thumbnailCache = NSCache<NSString, NSImage>()

    var supportsProtectedMetadata: Bool { entity.attributesByName["encryptedMetadata"] != nil }

    func readMetadata() throws -> ClipMetadata {
        if supportsProtectedMetadata, let ciphertext = encryptedMetadata {
            guard let id else { throw EncryptionManager.EncryptionError.invalidInput }
            if let cache = metadataCache, cache.id == id, cache.ciphertext == ciphertext {
                guard cache.metadata.contentHash == contentHash else { throw EncryptionManager.EncryptionError.invalidOutput }
                return cache.metadata
            }
            let data = try EncryptionManager.shared.decryptMetadata(ciphertext, itemID: id)
            let metadata = try JSONDecoder().decode(ClipMetadata.self, from: data)
            guard metadata.version == 1, metadata.contentHash == contentHash else { throw EncryptionManager.EncryptionError.invalidOutput }
            metadataCache = (id, ciphertext, metadata)
            return metadata
        }
        return ClipMetadata(dateAdded: dateAdded, firstCapturedAt: dateAdded, appBundleID: appBundleID, imageType: imageType)
    }

    func storeMetadata(_ metadata: ClipMetadata) throws {
        guard supportsProtectedMetadata, let id else { throw EncryptionManager.EncryptionError.invalidInput }
        var protected = metadata
        protected.contentHash = contentHash
        let data = try JSONEncoder().encode(protected)
        let ciphertext = try EncryptionManager.shared.encryptMetadata(data, itemID: id)
        encryptedMetadata = ciphertext
        dateAdded = nil
        appBundleID = nil
        imageType = nil
        metadataCache = (id, ciphertext, protected)
    }

    var displayDate: Date? { (try? readMetadata())?.dateAdded }
    var sourceAppBundleID: String? { (try? readMetadata())?.appBundleID }

    static func clearThumbnailCache() { thumbnailCache.removeAllObjects() }

    /// Returns the decrypted text content
    func getDecryptedText() -> String? {
        guard let encryptedData = textContent else { return nil }
        return try? EncryptionManager.shared.decryptString(encryptedData)
    }

    /// Sets the text content with encryption
    func setEncryptedText(_ text: String) throws {
        textContent = try EncryptionManager.shared.encryptString(text)
    }

    /// Returns the decrypted RTF data
    func getDecryptedRTF() -> Data? {
        guard let encryptedData = rtfData else { return nil }
        return try? EncryptionManager.shared.decrypt(encryptedData)
    }

    /// Sets the RTF data with encryption
    func setEncryptedRTF(_ data: Data) throws {
        rtfData = try EncryptionManager.shared.encrypt(data)
    }

    /// Decrypts image bytes only when needed for restoration or a thumbnail.
    func getDecryptedImage() -> (data: Data, type: NSPasteboard.PasteboardType)? {
        guard let encryptedData = imageData,
              let type = (try? readMetadata())?.imageType,
              let data = try? EncryptionManager.shared.decrypt(encryptedData) else { return nil }
        return (data, NSPasteboard.PasteboardType(type))
    }

    /// Encrypts the original pasteboard representation before assigning it to
    /// Core Data. Encryption failure therefore cannot fall back to plaintext.
    func setEncryptedImage(_ data: Data, type: NSPasteboard.PasteboardType) throws {
        let ciphertext = try EncryptionManager.shared.encrypt(data)
        if supportsProtectedMetadata {
            var metadata = try readMetadata()
            metadata.imageType = type.rawValue
            metadata.imageByteCount = Int64(ciphertext.count)
            try storeMetadata(metadata)
            imageByteCount = Int64(ciphertext.count)
        } else {
            imageType = type.rawValue
        }
        imageData = ciphertext
    }

    var isImage: Bool { imageData != nil }

    /// Creates a downsampled thumbnail without decoding the full-size screenshot.
    func getImageThumbnail(maxPixelSize: CGFloat = 160) -> NSImage? {
        let cacheKey = "\(objectID.uriRepresentation().absoluteString)-\(Int(maxPixelSize))" as NSString
        if let cached = Self.thumbnailCache.object(forKey: cacheKey) { return cached }
        guard let image = getDecryptedImage(),
              let source = CGImageSourceCreateWithData(image.data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixelSize,
            kCGImageSourceShouldCacheImmediately: true
        ]
        guard let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        let result = NSImage(cgImage: thumbnail, size: NSSize(width: thumbnail.width, height: thumbnail.height))
        Self.thumbnailCache.totalCostLimit = 16 * 1_024 * 1_024
        Self.thumbnailCache.setObject(result, forKey: cacheKey, cost: thumbnail.bytesPerRow * thumbnail.height)
        return result
    }

    /// Returns a preview string for display (truncated)
    func getPreviewText(maxLength: Int = 60) -> String {
        // Both text and RTF items have plain text stored in textContent
        if let text = getDecryptedText() {
            let preview = text.replacingOccurrences(of: "\n", with: " ")
            return preview.count > maxLength ? String(preview.prefix(maxLength)) + "..." : preview
        }
        return isImage ? "Image" : "[Unknown]"
    }

    /// Returns a relative time string (e.g., "2m ago", "1h ago")
    func getRelativeTimeString() -> String {
        guard let dateAdded = displayDate else { return "Unknown" }
        let now = Date()
        let interval = now.timeIntervalSince(dateAdded)

        let minutes = Int(interval / 60)
        let hours = Int(interval / 3600)
        let days = Int(interval / 86400)

        if minutes < 1 {
            return "Just now"
        } else if minutes < 60 {
            return "\(minutes)m ago"
        } else if hours < 24 {
            return "\(hours)h ago"
        } else if days < 7 {
            return "\(days)d ago"
        } else {
            let formatter = DateFormatter()
            formatter.dateStyle = .short
            formatter.timeStyle = .none
            return formatter.string(from: dateAdded)
        }
    }

    /// Computes SHA256 hash for deduplication
    static func computeHash(for data: Data) -> String {
        let hash = SHA256.hash(data: data)
        return hash.compactMap { String(format: "%02x", $0) }.joined()
    }

    /// Computes hash for a string
    static func computeHash(for string: String) -> String {
        guard let data = string.data(using: .utf8) else { return "" }
        return computeHash(for: data)
    }
}

// MARK: - Fetch Requests

extension ClipItem {

    /// Fetch all items sorted by date (pinned first)
    static func fetchAllRequest() -> NSFetchRequest<ClipItem> {
        let request = fetchRequest()
        // Protected timestamps are sorted in memory by the manager.
        return request
    }

    /// Fetch items matching a search query
    static func searchRequest(query: String) -> NSFetchRequest<ClipItem> {
        let request = fetchRequest()
        // Note: We can't search encrypted content directly, so this will be limited
        // In practice, we'll need to fetch all and decrypt in memory for search
        // Protected timestamps are sorted in memory by the manager.
        return request
    }

    /// Fetch item by hash for deduplication
    static func fetchByHashRequest(hash: String) -> NSFetchRequest<ClipItem> {
        let request = fetchRequest()
        request.predicate = NSPredicate(format: "contentHash == %@", hash)
        request.fetchLimit = 1
        return request
    }
}

// MARK: - Import CryptoKit for SHA256

import CryptoKit
